#!/usr/bin/env bash
set -eo pipefail

search_term=${1:-$(gum input --placeholder "Which command do you need to know about?")}

if [ -z "$search_term" ]; then
  exit 0
fi

output_command="curl -s "https://cheat.sh/$search_term" | less -R"

if [ -z "$TMUX" ]; then
  eval "$output_command"
  exit 0
fi

tmux split-window -h -p 50 "$output_command"
