return {
  "m4xshen/hardtime.nvim",
  event = "BufRead",
  dependencies = { "MunifTanjim/nui.nvim", "nvim-lua/plenary.nvim" },
  opts = {
    disable_mouse = false,
    -- restriction_mode = "hint",
    max_count = 10,
    allow_different_key = true,
    disabled_filetypes = {
      "NvimTree",
      "TelescopePrompt",
      "aerial",
      "alpha",
      "checkhealth",
      "dapui-repl",
      "dapui_breakpoints",
      "dapui_console",
      "dapui_scopes",
      "dapui_stacks",
      "dapui_watches",
      "DressingInput",
      "DressingSelect",
      "help",
      "lazy",
      "NeogitStatus",
      "NeogitLogView",
      "mason",
      "neotest-summary",
      "minifiles",
      "neo-tree",
      "neo-tree-popup",
      "netrw",
      "noice",
      "notify",
      "prompt",
      "qf",
      "oil",
      "undotree",
      "markdown.cody_history",
    },
  },
}
